name: meme_generator
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0-80.1.beta <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^2.2.0
  flutter_speed_dial: ^5.0.0+1
  carousel_slider: ^4.0.0
  cached_network_image: ^3.2.0
  image_picker: ^0.8.4+4
  fluttertoast: ^8.0.8
  share: ^2.0.4
  path_provider: ^2.0.3
  screenshot: ^1.2.3
  image_gallery_saver: '^1.6.9'
  permission_handler: any
  path: ^1.6.4
  path_provider_ex: ^1.0.1
  flutter_file_manager: ^0.2.0
  filesystem_picker: ^1.0.3
  ext_storage: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
    - images/
